# Generated by Django 4.2.3 on 2025-01-29 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_message', models.TextField(verbose_name='Start message')),
                ('subscribe_message', models.TextField(verbose_name='Subscribe message')),
                ('subscribe_button_text', models.CharField(max_length=255, verbose_name='Subscribe button text')),
                ('subscribe_button_link', models.URLField(verbose_name='Subscribe button link')),
                ('admin_chat_id', models.CharField(max_length=255, verbose_name='Admin chat id')),
                ('android_app_link', models.URLField(verbose_name='Android app link')),
                ('is_send_delay_message', models.BooleanField(default=False, verbose_name='Send delay message')),
                ('delay_seconds', models.PositiveIntegerField(default=0, verbose_name='Delay seconds')),
                ('media', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], max_length=10, verbose_name='Media type')),
                ('media_file', models.FileField(upload_to='media_files', verbose_name='Media file')),
                ('message', models.TextField(verbose_name='Message')),
                ('button_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Button text')),
                ('button_link', models.URLField(blank=True, null=True, verbose_name='Button link')),
                ('media_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Media ID')),
            ],
            options={
                'verbose_name': 'Bot Configuration',
            },
        ),
        migrations.DeleteModel(
            name='DelayMessage',
        ),
        migrations.DeleteModel(
            name='ScheduledMessage',
        ),
        migrations.DeleteModel(
            name='SubscribeChannel',
        ),
        migrations.RemoveField(
            model_name='usercode',
            name='user',
        ),
        migrations.DeleteModel(
            name='TelegramUser',
        ),
        migrations.DeleteModel(
            name='UserCode',
        ),
    ]
