# Generated by Django 4.2.3 on 2025-01-29 06:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_botconfiguration_delete_delaymessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=255, verbose_name='Chat ID')),
                ('username', models.CharField(max_length=255, verbose_name='Username')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('language_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Language Code')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Telegram User',
                'verbose_name_plural': 'Telegram Users',
            },
        ),
        migrations.AlterModelOptions(
            name='botconfiguration',
            options={'verbose_name': 'Bot Configuration', 'verbose_name_plural': 'Bot Configurations'},
        ),
        migrations.RemoveField(
            model_name='botconfiguration',
            name='android_app_link',
        ),
        migrations.RemoveField(
            model_name='botconfiguration',
            name='button_link',
        ),
        migrations.RemoveField(
            model_name='botconfiguration',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='botconfiguration',
            name='delay_seconds',
        ),
        migrations.RemoveField(
            model_name='botconfiguration',
            name='is_send_delay_message',
        ),
        migrations.RemoveField(
            model_name='botconfiguration',
            name='media',
        ),
        migrations.RemoveField(
            model_name='botconfiguration',
            name='media_file',
        ),
        migrations.RemoveField(
            model_name='botconfiguration',
            name='media_id',
        ),
        migrations.RemoveField(
            model_name='botconfiguration',
            name='message',
        ),
        migrations.RemoveField(
            model_name='botconfiguration',
            name='start_message',
        ),
        migrations.RemoveField(
            model_name='botconfiguration',
            name='subscribe_button_link',
        ),
        migrations.RemoveField(
            model_name='botconfiguration',
            name='subscribe_button_text',
        ),
        migrations.RemoveField(
            model_name='botconfiguration',
            name='subscribe_message',
        ),
        migrations.AddField(
            model_name='botconfiguration',
            name='channel_id',
            field=models.CharField(default='', max_length=255, verbose_name='Channel ID'),
        ),
        migrations.AlterField(
            model_name='botconfiguration',
            name='admin_chat_id',
            field=models.CharField(max_length=255, verbose_name='Admin Chat ID'),
        ),
        migrations.CreateModel(
            name='ScheduledMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('photo', 'Photo'), ('video', 'Video')], max_length=5, verbose_name='Message Type')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('media_file', models.FileField(blank=True, null=True, upload_to='media_files', verbose_name='Media File')),
                ('scheduled_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Scheduled Time')),
                ('button_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Button Text')),
                ('button_link', models.URLField(blank=True, null=True, verbose_name='Button Link')),
                ('additional_media', models.FileField(blank=True, null=True, upload_to='media_files', verbose_name='Additional Media')),
                ('is_send', models.BooleanField(default=False, verbose_name='Send')),
                ('media_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Media ID')),
                ('bot_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to='bot.botconfiguration')),
            ],
            options={
                'verbose_name': 'Scheduled Message',
                'verbose_name_plural': 'Scheduled Messages',
            },
        ),
        migrations.CreateModel(
            name='DelayMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('photo', 'Photo'), ('video', 'Video')], max_length=5, verbose_name='Message Type')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('media_file', models.FileField(blank=True, null=True, upload_to='media_files', verbose_name='Media File')),
                ('scheduled_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Scheduled Time')),
                ('button_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Button Text')),
                ('button_link', models.URLField(blank=True, null=True, verbose_name='Button Link')),
                ('additional_media', models.FileField(blank=True, null=True, upload_to='media_files', verbose_name='Additional Media')),
                ('is_send', models.BooleanField(default=False, verbose_name='Send')),
                ('media_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Media ID')),
                ('bot_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delay_messages', to='bot.botconfiguration')),
            ],
            options={
                'verbose_name': 'Delay Message',
                'verbose_name_plural': 'Delay Messages',
            },
        ),
    ]
