# Generated by Django 4.2.3 on 2025-01-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_telegramuser_language_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='status',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='chat_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='language_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
