# Generated by Django 4.2.3 on 2025-01-29 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_remove_telegramuser_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'ordering': ['-created_at'], 'verbose_name': 'Telegram User', 'verbose_name_plural': 'Telegram Users'},
        ),
        migrations.RemoveField(
            model_name='scheduledmessage',
            name='additional_media',
        ),
        migrations.RemoveField(
            model_name='scheduledmessage',
            name='button_link',
        ),
        migrations.RemoveField(
            model_name='scheduledmessage',
            name='button_text',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='botconfiguration',
            name='admin_chat_id',
            field=models.BigIntegerField(default=0, verbose_name='Admin Chat ID'),
        ),
        migrations.AlterField(
            model_name='botconfiguration',
            name='channel_id',
            field=models.BigIntegerField(default=0, verbose_name='Channel ID'),
        ),
        migrations.AlterField(
            model_name='button',
            name='next_support',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_support_buttons', to='bot.button'),
        ),
        migrations.AlterField(
            model_name='button',
            name='support',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_buttons', to='bot.button'),
        ),
        migrations.AlterField(
            model_name='delaymessage',
            name='bot_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_messages', to='bot.botconfiguration'),
        ),
        migrations.AlterField(
            model_name='delaymessage',
            name='media_id',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Media ID'),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='bot_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_messages', to='bot.botconfiguration'),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='media_id',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Media ID'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='chat_id',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='language_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
