# Generated by Django 4.2.3 on 2025-01-29 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_alter_telegramuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmessage',
            name='additional_media',
            field=models.FileField(blank=True, null=True, upload_to='media_files', verbose_name='Additional Media'),
        ),
        migrations.AddField(
            model_name='scheduledmessage',
            name='button_link',
            field=models.URLField(blank=True, null=True, verbose_name='Button Link'),
        ),
        migrations.AddField(
            model_name='scheduledmessage',
            name='button_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Button Text'),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='bot_configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to='bot.botconfiguration'),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='media_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Media ID'),
        ),
    ]
