# Generated by Django 4.2.3 on 2025-01-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_scheduledmessage_additional_media_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
